Add Ubuntu 20.04 support
ghoneycutt/puppet-module-ssh pull request #343
Opened 2020-06-11 19:05 UTC by mergwyn

2020-06-11 19:14 UTC, ghoneycutt commented
Thanks for the contribution! Are these fixtures from a default, stock install of the platform?

2020-06-11 19:16 UTC, ghoneycutt commented
I just merged Debian 10 access which has a small merge conflict. Could you please rebase and I'll get this going.

2020-06-11 19:21 UTC, mergwyn commented
I just copied the 18.04 settings across. I tried it on the two 20.04 machines I have so far (1 physical, 1 lxc, both fresh install) with no apparent issues. I’ll get on to rebasing.

2020-06-11 19:32 UTC, ghoneycutt commented
Were the fixtures files coped from 18 or are they from an actual 20.04 system?

2020-06-11 19:38 UTC, mergwyn commented
Copied from 18

2020-06-11 19:38 UTC, mergwyn commented
How do I generate fixtures from a 20.04 system?

2020-06-11 19:59 UTC, ghoneycutt commented
You copy the actual ssh_config and sshd_config files.

2020-06-11 20:11 UTC, mergwyn commented
I've copied across clean versions of the config files. Do I then need to fix the defaults in init.pp to match the fixtures?

2020-06-11 20:14 UTC, ghoneycutt commented
Yep :)

2020-06-12 16:13 UTC, mergwyn commented
The issue I am having is that Canonical has tidied up the two config files and left many options disabled by default.  As an example, the non comment lines in 20.04 sshd_config are:
```
Include /etc/ssh/sshd_config.d/*.conf
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem	sftp	/usr/lib/openssh/sftp-server
```
So not much is enabled out of the box. The equivalent for 18.04 is:
```
Port 22
Protocol 2
AddressFamily any
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
PubkeyAuthentication yes
HostbasedAuthentication no
IgnoreUserKnownHosts no
IgnoreRhosts yes
PasswordAuthentication yes
ChallengeResponseAuthentication yes
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
UsePAM yes
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL
AllowTcpForwarding yes
X11Forwarding yes
X11UseLocalhost yes
PrintMotd yes
TCPKeepAlive yes
ClientAliveInterval 0
ClientAliveCountMax 3
UseDNS yes
PermitTunnel no
Banner none
Subsystem sftp /usr/lib/openssh/sftp-server
```
In order to achieve this significant extensions would be required to the module (eg allowing many more options to be unset completely, potentially disrupting support for other OS.  My instinct is not to do this! I'd really welcome some guidance on how to proceed.  Thanks

2020-06-22 06:45 UTC, dsundq commented
Hi,
We are interested to get ssh module working with Ubuntu 20.04, any updates?
Thanks :)

2020-06-29 07:47 UTC, mergwyn commented
I’ll try and get this finalised and submitted for @ghoneycutt to review this week.

2020-07-06 19:57 UTC, mergwyn commented
I've taken aligning the fixtures version of the config files as far as I can without significant rework and refactoring across the module. As I said in an an earlier comment Ubuntu 20.04 has cleaned up the ssh and ssh config files and not included settings where they are the same as defaults (shown as comments).  As far as I can tell there is no functional differences between the 20.04 defaults and the settings produced by this module. 

Here are some of the differences that I have not addressed.
ssh_confg:
  20.04 has ’Host *’ before all settings - the template is not set up in this way

sshd_config:
No easy way to unset port 22
There is currently no way to set these variables:

- Procotol
- AcceptEnv LANG

There is currently no way to set OS specific default values for:

- Syslog Facility
- LogLevel
- LoginGraceTime
- PermitRootLogin
- PubkeyAuthentication
- HostbasedAuthentication
- IgnoreUserKnownHosts
- IgnoreRhosts
- PasswordAuthentication
- ChallengeResponseAuthentication
- GSSAPIAuthentication
- AllowTcpForwarding
- X11Forwarding
- X11UseLocalhost
- PrintMotd
- ClientAliveInterval
- ClientAliveCountMax
- Banner

Some have comments inside conditional and so you can’t undef them without removing the comments and requiring other fixture config files to be update:

- AddressFamily
- GSSAPICleanupCredentials
- UsePAM
- UseDNS

2020-07-07 13:00 UTC, mergwyn commented
Hi, the checks are finally passing after lots of problems trying to squash the commits into 1.  Are you able to do a merge and squash via the web interface when you are happy, or do you need me to do something to tidy up the history? If the latter, what, as I seem to be getting myself into a mess trying this!

2020-07-07 13:01 UTC, mergwyn commented
BTW, my master branch now has this branch squashed into a single commit but I don't know if it is possible to change the branch that this PR points to.

2020-07-24 09:43 UTC, anders-larsson commented
@ghoneycutt  Can you have another look? What's missing if anything? Thanks!

2020-08-30 14:01 UTC, raoulbhatia commented
I'd also like to see Ubuntu 20.04 support but am not sure which changes should now be reviewed / merged.

`mergwyn:PR343_merge` or `mergwyn:master`?

Raoul

2020-08-31 07:58 UTC, mergwyn commented
PR343_merge please

2020-09-04 03:19 UTC, ghoneycutt requested changes

2020-09-04 03:19 UTC, ghoneycutt commented on types/include.pp
> +# config files to be includes
This would break puppet3, so please remove it.

2020-09-04 03:19 UTC, ghoneycutt commented on templates/ssh_config.erb
> +<% if defined?(@ssh_config_include_real) -%>
There needs to be corresponding spec tests for these that show what happens when this is undef, string or array.

2020-09-07 18:29 UTC, ghoneycutt approved these changes

2020-09-07 18:29 UTC, ghoneycutt commented
Thanks @mergwyn !!

2020-09-07 18:29 UTC, merged

2020-09-07 18:33 UTC, ghoneycutt commented
Released as v3.62.0